export const bgColor = '#FFE0DB'
export const deckBgColor = '#F1A7A5'
export const textColor = '#411218'
export const inActiveColor = '#F58786'
export const headingColor = '#f04a4f'
export const white ='#fff'
export const black = '#000'